name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Match this to your project's Java version
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x AndroidKeylogger/gradlew

      - name: Build Debug APK
        run: AndroidKeylogger/gradlew :app:assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
